//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kokoava.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kokoava.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaa....
        /// </summary>
        public static string Avaa {
            get {
                return ResourceManager.GetString("Avaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopeta.
        /// </summary>
        public static string Lopeta {
            get {
                return ResourceManager.GetString("Lopeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piirrä.
        /// </summary>
        public static string Piirrä {
            get {
                return ResourceManager.GetString("Piirrä", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puhdista ruutu.
        /// </summary>
        public static string puhdista_ruutu {
            get {
                return ResourceManager.GetString("puhdista_ruutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyyhi.
        /// </summary>
        public static string Pyyhi {
            get {
                return ResourceManager.GetString("Pyyhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siveltimen koko.
        /// </summary>
        public static string siveltimen_koko {
            get {
                return ResourceManager.GetString("siveltimen_koko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siveltimen väri.
        /// </summary>
        public static string siveltimen_vari {
            get {
                return ResourceManager.GetString("siveltimen_vari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallenna.
        /// </summary>
        public static string Tallenna {
            get {
                return ResourceManager.GetString("Tallenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiedosto.
        /// </summary>
        public static string Tiedosto {
            get {
                return ResourceManager.GetString("Tiedosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse.
        /// </summary>
        public static string Valitse {
            get {
                return ResourceManager.GetString("Valitse", resourceCulture);
            }
        }
    }
}
